name: AybCache.CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest                           

    env:
      Build_Config: Release
      Solution: AybCache.sln
      Test_Project_Path: AybCache.Tests\AybCache.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Restore dependencies
      run: nuget restore $Solution
      
    - name: Build
      run: dotnet build $Solution --configuration $Build_Config --no-restore
